version: "3.7"

services:
  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gis_myself_network
    volumes:
      - /home/rmmmm.9/nginx.conf:/etc/nginx/nginx.conf
      - gis_myself_static:/data/static/
      - gis_myself_media:/data/media/

  django:
    image: gis-myself:3
    networks:
      - gis_myself_network
    volumes:
      - gis_myself_static:/home/WebApplication_Myself/staticfiles/
      - gis_myself_media:/home/WebApplication_Myself/media/

networks:
  gis_myself_network:

volumes:
  gis_myself_static:
  gis_myself_media: